// <auto-generated />
using DotNetStripe.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotNetStripe.Server.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DotNetStripe.Shared.Models.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = "25a8358b-36b3-48e2-8301-127ac0806e30",
                            Description = "Description of product 0, This is an amazing product with a price-quality balance you won't find anywhere else.",
                            ImageUrl = "https://picsum.photos/id/0/500",
                            Price = 1000m,
                            Title = "Product 0"
                        },
                        new
                        {
                            Id = "25a8358b-36b3-48e2-8301-127ac0806e31",
                            Description = "Description of product 1, This is an amazing product with a price-quality balance you won't find anywhere else.",
                            ImageUrl = "https://picsum.photos/id/1/500",
                            Price = 1001m,
                            Title = "Product 1"
                        },
                        new
                        {
                            Id = "25a8358b-36b3-48e2-8301-127ac0806e32",
                            Description = "Description of product 2, This is an amazing product with a price-quality balance you won't find anywhere else.",
                            ImageUrl = "https://picsum.photos/id/2/500",
                            Price = 1002m,
                            Title = "Product 2"
                        },
                        new
                        {
                            Id = "25a8358b-36b3-48e2-8301-127ac0806e33",
                            Description = "Description of product 3, This is an amazing product with a price-quality balance you won't find anywhere else.",
                            ImageUrl = "https://picsum.photos/id/3/500",
                            Price = 1003m,
                            Title = "Product 3"
                        },
                        new
                        {
                            Id = "25a8358b-36b3-48e2-8301-127ac0806e34",
                            Description = "Description of product 4, This is an amazing product with a price-quality balance you won't find anywhere else.",
                            ImageUrl = "https://picsum.photos/id/4/500",
                            Price = 1004m,
                            Title = "Product 4"
                        },
                        new
                        {
                            Id = "25a8358b-36b3-48e2-8301-127ac0806e35",
                            Description = "Description of product 5, This is an amazing product with a price-quality balance you won't find anywhere else.",
                            ImageUrl = "https://picsum.photos/id/5/500",
                            Price = 1005m,
                            Title = "Product 5"
                        },
                        new
                        {
                            Id = "25a8358b-36b3-48e2-8301-127ac0806e36",
                            Description = "Description of product 6, This is an amazing product with a price-quality balance you won't find anywhere else.",
                            ImageUrl = "https://picsum.photos/id/6/500",
                            Price = 1006m,
                            Title = "Product 6"
                        },
                        new
                        {
                            Id = "25a8358b-36b3-48e2-8301-127ac0806e37",
                            Description = "Description of product 7, This is an amazing product with a price-quality balance you won't find anywhere else.",
                            ImageUrl = "https://picsum.photos/id/7/500",
                            Price = 1007m,
                            Title = "Product 7"
                        },
                        new
                        {
                            Id = "25a8358b-36b3-48e2-8301-127ac0806e38",
                            Description = "Description of product 8, This is an amazing product with a price-quality balance you won't find anywhere else.",
                            ImageUrl = "https://picsum.photos/id/8/500",
                            Price = 1008m,
                            Title = "Product 8"
                        },
                        new
                        {
                            Id = "25a8358b-36b3-48e2-8301-127ac0806e39",
                            Description = "Description of product 9, This is an amazing product with a price-quality balance you won't find anywhere else.",
                            ImageUrl = "https://picsum.photos/id/9/500",
                            Price = 1009m,
                            Title = "Product 9"
                        },
                        new
                        {
                            Id = "25a8358b-36b3-48e2-8301-127ac0806e310",
                            Description = "Description of product 10, This is an amazing product with a price-quality balance you won't find anywhere else.",
                            ImageUrl = "https://picsum.photos/id/10/500",
                            Price = 1010m,
                            Title = "Product 10"
                        },
                        new
                        {
                            Id = "25a8358b-36b3-48e2-8301-127ac0806e311",
                            Description = "Description of product 11, This is an amazing product with a price-quality balance you won't find anywhere else.",
                            ImageUrl = "https://picsum.photos/id/11/500",
                            Price = 1011m,
                            Title = "Product 11"
                        },
                        new
                        {
                            Id = "25a8358b-36b3-48e2-8301-127ac0806e312",
                            Description = "Description of product 12, This is an amazing product with a price-quality balance you won't find anywhere else.",
                            ImageUrl = "https://picsum.photos/id/12/500",
                            Price = 1012m,
                            Title = "Product 12"
                        },
                        new
                        {
                            Id = "25a8358b-36b3-48e2-8301-127ac0806e313",
                            Description = "Description of product 13, This is an amazing product with a price-quality balance you won't find anywhere else.",
                            ImageUrl = "https://picsum.photos/id/13/500",
                            Price = 1013m,
                            Title = "Product 13"
                        },
                        new
                        {
                            Id = "25a8358b-36b3-48e2-8301-127ac0806e314",
                            Description = "Description of product 14, This is an amazing product with a price-quality balance you won't find anywhere else.",
                            ImageUrl = "https://picsum.photos/id/14/500",
                            Price = 1014m,
                            Title = "Product 14"
                        },
                        new
                        {
                            Id = "25a8358b-36b3-48e2-8301-127ac0806e315",
                            Description = "Description of product 15, This is an amazing product with a price-quality balance you won't find anywhere else.",
                            ImageUrl = "https://picsum.photos/id/15/500",
                            Price = 1015m,
                            Title = "Product 15"
                        },
                        new
                        {
                            Id = "25a8358b-36b3-48e2-8301-127ac0806e316",
                            Description = "Description of product 16, This is an amazing product with a price-quality balance you won't find anywhere else.",
                            ImageUrl = "https://picsum.photos/id/16/500",
                            Price = 1016m,
                            Title = "Product 16"
                        },
                        new
                        {
                            Id = "25a8358b-36b3-48e2-8301-127ac0806e317",
                            Description = "Description of product 17, This is an amazing product with a price-quality balance you won't find anywhere else.",
                            ImageUrl = "https://picsum.photos/id/17/500",
                            Price = 1017m,
                            Title = "Product 17"
                        },
                        new
                        {
                            Id = "25a8358b-36b3-48e2-8301-127ac0806e318",
                            Description = "Description of product 18, This is an amazing product with a price-quality balance you won't find anywhere else.",
                            ImageUrl = "https://picsum.photos/id/18/500",
                            Price = 1018m,
                            Title = "Product 18"
                        },
                        new
                        {
                            Id = "25a8358b-36b3-48e2-8301-127ac0806e319",
                            Description = "Description of product 19, This is an amazing product with a price-quality balance you won't find anywhere else.",
                            ImageUrl = "https://picsum.photos/id/19/500",
                            Price = 1019m,
                            Title = "Product 19"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
